=== DanielRamosAcosta/nas-k3s/lib/media/beets.config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "plugins": {
      "type": "string",
      "description": "A space-separated list of plugin module names to load"
    },
    "directory": {
      "type": "string",
      "description": "The directory to which files will be copied/moved when adding them to the library. Defaults to a folder called Music in your home directory."
    },
    "library": {
      "type": "string",
      "description": "Path to the beets library file. By default, beets will use a file called library.db alongside your configuration file."
    },
    "art_filename": {
      "type": "string",
      "description": "When importing album art, the name of the file (without extension) where the cover art image should be placed. This is a template string, so you can use any of the syntax available to Path Formats. Defaults to cover (i.e., images will be named cover.jpg or cover.png and placed in the album’s directory)."
    },
    "threaded": {
      "type": "boolean",
      "description": "Either yes or no, indicating whether the autotagger should use multiple threads. This makes things substantially faster by overlapping work: for example, it can copy files for one album in parallel with looking up data in MusicBrainz for a different album. You may want to disable this when debugging problems with the autotagger. Defaults to yes."
    },
    "original_date": {
      "type": "boolean",
      "description": "Either yes or no, indicating whether matched albums should have their year, month, and day fields set to the release date of the original version of an album rather than the selected version of the release. That is, if this option is turned on, then year will always equal original_year and so on. Default: no."
    },
    "per_disc_numbering": {
      "type": "boolean",
      "description": "A boolean controlling the track numbering style on multi-disc releases. By default (per_disc_numbering: no), tracks are numbered per-release, so the first track on the second disc has track number N+1 where N is the number of tracks on the first disc. If this per_disc_numbering is enabled, then the first (non-pregap) track on each disc always has track number 1.\nIf you enable per_disc_numbering, you will likely want to change your Path Format Configuration also to include $disc before $track to make filenames sort correctly in album directories"
    },
    "convert": {
      "type": "object",
      "properties": {
        "auto": {
          "type": "boolean"
        },
        "ffmpeg": {
          "type": "string"
        },
        "opts": {
          "type": "string"
        },
        "max_bitrate": {
          "type": "number"
        },
        "threads": {
          "type": "number"
        }
      },
      "required": [
        "auto",
        "ffmpeg",
        "opts",
        "max_bitrate",
        "threads"
      ]
    },
    "paths": {
      "type": "object",
      "properties": {
        "comp": {
          "type": "string"
        },
        "singleton": {
          "type": "string"
        },
        "albumtype:single": {
          "type": "string"
        },
        "default": {
          "type": "string"
        }
      },
      "required": [
        "comp",
        "singleton",
        "albumtype:single",
        "default"
      ]
    },
    "import": {
      "type": "object",
      "properties": {
        "write": {
          "type": "boolean",
          "description": "Either yes or no, controlling whether metadata (e.g., ID3) tags are written to files when using beet import. Defaults to yes. The -w and -W command-line options override this setting."
        },
        "copy": {
          "type": "boolean",
          "description": "Either yes or no, indicating whether to copy files into the library directory when using beet import. Defaults to yes. Can be overridden with the -c and -C command-line options. The option is ignored if move is enabled (i.e., beets can move or copy files but it doesn’t make sense to do both)."
        },
        "move": {
          "type": "boolean",
          "description": "Either yes or no, indicating whether to move files into the library directory when using beet import. Defaults to no.\n\nThe effect is similar to the copy option but you end up with only one copy of the imported file. (“Moving” works even across filesystems; if necessary, beets will copy and then delete when a simple rename is impossible.) Moving files can be risky—it’s a good idea to keep a backup in case beets doesn’t do what you expect with your files.\n\nThis option overrides copy, so enabling it will always move (and not copy) files. The -c switch to the beet import command, however, still takes precedence."
        },
        "resume": {
          "type": "string",
          "description": "Either yes, no, or ask. Controls whether interrupted imports should be resumed. “Yes” means that imports are always resumed when possible; “no” means resuming is disabled entirely; “ask” (the default) means that the user should be prompted when resuming is possible. The -p and -P flags correspond to the “yes” and “no” settings and override this option."
        },
        "incremental": {
          "type": "boolean",
          "description": "Either yes or no, controlling whether imported directories are recorded and whether these recorded directories are skipped. This corresponds to the -i flag to beet import."
        },
        "quiet_fallback": {
          "type": "string",
          "enum": ["skip", "asis"],
          "description": "Either skip (default) or asis, specifying what should happen in quiet mode (see the -q flag to import, above) when there is no strong recommendation."
        },
        "timid": {
          "type": "boolean",
          "description": "Either yes or no, controlling whether the importer runs in timid mode, in which it asks for confirmation on every autotagging match, even the ones that seem very close. Defaults to no"
        },
        "log": {
          "type": "string",
          "description": "Specifies a filename where the importer’s log should be kept. By default, no log is written. This can be overridden with the -l flag to import."
        }
      },
      "required": [
        "write",
        "copy",
        "move",
        "resume",
        "incremental",
        "quiet_fallback",
        "timid",
        "log"
      ]
    },
    "lastgenre": {
      "type": "object",
      "properties": {
        "auto": {
          "type": "boolean"
        },
        "source": {
          "type": "string"
        }
      },
      "required": [
        "auto",
        "source"
      ]
    },
    "embedart": {
      "type": "object",
      "properties": {
        "auto": {
          "type": "boolean"
        }
      },
      "required": [
        "auto"
      ]
    },
    "fetchart": {
      "type": "object",
      "properties": {
        "auto": {
          "type": "boolean"
        }
      },
      "required": [
        "auto"
      ]
    },
    "replaygain": {
      "type": "object",
      "properties": {
        "auto": {
          "type": "boolean"
        },
        "command": {
          "type": "string"
        }
      },
      "required": [
        "auto",
        "command"
      ]
    },
    "scrub": {
      "type": "object",
      "properties": {
        "auto": {
          "type": "boolean"
        }
      },
      "required": [
        "auto"
      ]
    },
    "replace": {
      "type": "object",
      "properties": {
        "^\\.": {
          "type": "string"
        },
        "[\\x00-\\x1f]": {
          "type": "string"
        },
        "[<>:\"\\?\\*\\|]": {
          "type": "string"
        },
        "[\\xE8-\\xEB]": {
          "type": "string"
        },
        "[\\xEC-\\xEF]": {
          "type": "string"
        },
        "[\\xE2-\\xE6]": {
          "type": "string"
        },
        "[\\xF2-\\xF6]": {
          "type": "string"
        },
        "[\\xF8]": {
          "type": "string"
        },
        "\\.$": {
          "type": "string"
        },
        "\\s+$": {
          "type": "string"
        }
      },
      "required": [
        "^\\.",
        "[\\x00-\\x1f]",
        "[<>:\"\\?\\*\\|]",
        "[\\xE8-\\xEB]",
        "[\\xEC-\\xEF]",
        "[\\xE2-\\xE6]",
        "[\\xF2-\\xF6]",
        "[\\xF8]",
        "\\.$",
        "\\s+$"
      ]
    },
    "web": {
      "type": "object",
      "properties": {
        "host": {
          "type": "string"
        },
        "port": {
          "type": "number"
        }
      },
      "required": [
        "host",
        "port"
      ]
    },
    "match": {
      "type": "object",
      "properties": {
        "strong_rec_thresh": {
          "type": "number"
        },
        "medium_rec_thresh": {
          "type": "number"
        },
        "rec_gap_thresh": {
          "type": "number"
        },
        "distance_weights": {
          "type": "object",
          "properties": {
            "source": {
              "type": "number"
            },
            "artist": {
              "type": "number"
            },
            "album": {
              "type": "number"
            },
            "media": {
              "type": "number"
            },
            "mediums": {
              "type": "number"
            },
            "year": {
              "type": "number"
            },
            "country": {
              "type": "number"
            },
            "label": {
              "type": "number"
            },
            "catalognum": {
              "type": "number"
            },
            "albumdisambig": {
              "type": "number"
            },
            "album_id": {
              "type": "number"
            },
            "tracks": {
              "type": "number"
            },
            "missing_tracks": {
              "type": "number"
            },
            "unmatched_tracks": {
              "type": "number"
            },
            "track_title": {
              "type": "number"
            },
            "track_artist": {
              "type": "number"
            },
            "track_index": {
              "type": "number"
            },
            "track_length": {
              "type": "number"
            },
            "track_id": {
              "type": "number"
            }
          },
          "required": [
            "source",
            "artist",
            "album",
            "media",
            "mediums",
            "year",
            "country",
            "label",
            "catalognum",
            "albumdisambig",
            "album_id",
            "tracks",
            "missing_tracks",
            "unmatched_tracks",
            "track_title",
            "track_artist",
            "track_index",
            "track_length",
            "track_id"
          ]
        }
      },
      "required": [
        "strong_rec_thresh",
        "medium_rec_thresh",
        "rec_gap_thresh",
        "distance_weights"
      ]
    }
  },
  "required": []
}

=== DanielRamosAcosta/nas-k3s/lib/media/beets.config.json
{
    "$schema": "./beets.config.schema.json",
    "plugins": "musicbrainz fetchart embedart convert scrub replaygain lastgenre chroma web missing",
    "directory": "/music",
    "library": "/data/musiclibrary.blb",
    "art_filename": "albumart",
    "threaded": true,
    "original_date": false,
    "per_disc_numbering": false,
    "convert": {
        "auto": false,
        "ffmpeg": "/usr/bin/ffmpeg",
        "opts": "-ab 320k -ac 2 -ar 48000",
        "max_bitrate": 320,
        "threads": 1
    },
    "paths": {
        "comp": "$albumartist/$albumtype/$album ($year)/$albumartist - $album - $track - $title",
        "singleton": "$albumartist/Single/$album ($year)/$albumartist - $album - $track - $title",
        "albumtype:single": "$albumartist/Single/$album ($year)/$albumartist - $album - $track - $title",
        "default": "$albumartist/Album/$album ($year)/$albumartist - $album - $track - $title"
    },
    "import": {
        "write": true,
        "copy": false,
        "move": false,
        "resume": "ask",
        "incremental": true,
        "quiet_fallback": "skip",
        "timid": true,
        "log": "/data/beet.log"
    },
    "lastgenre": {
        "auto": false,
        "source": "album"
    },
    "embedart": {
        "auto": true
    },
    "fetchart": {
        "auto": true
    },
    "replaygain": {
        "auto": false,
        "command": "mp3gain"
    },
    "scrub": {
        "auto": true
    },
    "replace": {
        "^\\.": "_",
        "[\\x00-\\x1f]": "_",
        "[<>:\"\\?\\*\\|]": "_",
        "[\\xE8-\\xEB]": "e",
        "[\\xEC-\\xEF]": "i",
        "[\\xE2-\\xE6]": "a",
        "[\\xF2-\\xF6]": "o",
        "[\\xF8]": "o",
        "\\.$": "_",
        "\\s+$": ""
    },
    "web": {
        "host": "0.0.0.0",
        "port": 8337
    }
}
